server:
  port: 8082
spring:
  application:
    name: good-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tx-lcn-service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true&serverTimezone=UTC
      password: root
      username: root
      platform: all
      type: com.alibaba.druid.pool.DruidDataSource


tx-lcn:
  client:
    manager-address: localhost:8070 #指定TM端口 集群向后逗号分隔
  ribbon:
    loadbalancer:
      dtx:
        enabled: true                  #开启启动LCN负载均衡策略